<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Recipe;
use App\Models\Category;
use App\Models\Ingredient;
use App\Models\User;
use Illuminate\Support\Str;

class RecipesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Create the primary admin user "Yahya"
        $admin = User::firstOrCreate(['email' => 'yahyadaraan@gmail.com'], [
            'name' => 'Yahya',
            'password' => \Illuminate\Support\Facades\Hash::make('yahya'),
        ]);

        $recipesData = [
            // --- ITALIAN ---
            [ 'category' => "Italian", 'title' => "Classic Margherita Pizza", 'image' => "https://images.unsplash.com/photo-1574071318508-1cdbab80d002", 'meta' => [ 'time' => "45", 'servings' => "2", 'calories' => "600" ], 'ingredients' => [[ 'name' => "Pizza Dough", 'amount' => "1 ball" ], [ 'name' => "Mozzarella", 'amount' => "200g" ], [ 'name' => "Basil", 'amount' => "Fresh" ]], 'instructions' => ["Preheat your oven to its highest setting (usually 250°C/480°F).", "Roll out the pizza dough on a floured surface to your desired thickness.", "Spread a thin layer of tomato sauce over the base, leaving a crust at the edges.", "Tear fresh mozzarella and basil evenly over the sauce.", "Bake for 10-12 minutes until the crust is golden and cheese is bubbly.", "Top with fresh basil leaves before serving."] ],
            [ 'category' => "Italian", 'title' => "Creamy Carbonara", 'image' => "https://images.unsplash.com/photo-1612874742237-6526221588e3", 'meta' => [ 'time' => "20", 'servings' => "2", 'calories' => "550" ], 'ingredients' => [[ 'name' => "Pasta (Spaghetti)", 'amount' => "200g" ], [ 'name' => "Eggs", 'amount' => "2" ], [ 'name' => "Pancetta", 'amount' => "100g" ]], 'instructions' => ["Bring a large pot of salted water to a boil and cook spaghetti until al dente.", "While pasta cooks, fry pancetta in a pan until crisp and golden.", "In a bowl, whisk eggs with grated Pecorino/Parmesan cheese and black pepper.", "Drain pasta, reserving some cooking water. Toss pasta directly into the pancetta pan.", "Remove from heat. Quickly mix in the egg mixture, adding pasta water to create a creamy sauce.", "Serve immediately with extra black pepper."] ],
            [ 'category' => "Italian", 'title' => "Mushroom Risotto", 'image' => "https://images.unsplash.com/photo-1476124369491-e7addf5db371", 'meta' => [ 'time' => "40", 'servings' => "4", 'calories' => "500" ], 'ingredients' => [[ 'name' => "Arborio Rice", 'amount' => "2 cups" ], [ 'name' => "Mushrooms", 'amount' => "500g" ], [ 'name' => "Broth", 'amount' => "1L" ]], 'instructions' => ["Sauté sliced mushrooms in butter/oil until browned; set aside.", "In the same pan, toast Arborio rice for 1-2 minutes until translucent at edges.", "Add warm broth one ladle at a time, stirring constantly until absorbed.", "Continue this process for about 20 minutes until rice is creamy but al dente.", "Stir the mushrooms back in, add parmesan and butter, and serve warm."] ],
            [ 'category' => "Italian", 'title' => "Lasagna Classico", 'image' => "images/ingredients/Pizza Dough.jpg", 'meta' => [ 'time' => "90", 'servings' => "6", 'calories' => "700" ], 'ingredients' => [[ 'name' => "Lasagna Sheets", 'amount' => "1 box" ], [ 'name' => "Bolognese Sauce", 'amount' => "500g" ], [ 'name' => "Bechamel", 'amount' => "500g" ]], 'instructions' => ["Preheat oven to 180°C (350°F).", "Spread a thin layer of meat sauce on the bottom of a baking dish.", "Layer lasagna sheets, meat sauce, bechamel, and parmesan.", "Repeat layers until all ingredients are used, finishing with bechamel and cheese.", "Bake for 40-45 minutes until golden brown and bubbly. Let rest for 10 mins before slicing."] ],
            [ 'category' => "Italian", 'title' => "Caprese Salad", 'image' => "images/ingredients/Mozzarella.webp", 'meta' => [ 'time' => "10", 'servings' => "2", 'calories' => "250" ], 'ingredients' => [[ 'name' => "Mozzarella", 'amount' => "200g" ], [ 'name' => "Tomato", 'amount' => "3" ], [ 'name' => "Basil", 'amount' => "Bunch" ]], 'instructions' => ["Slice fresh mozzarella and tomatoes into even rounds.", "On a large platter, arrange tomato and cheese slices in an alternating pattern.", "Tuck fresh basil leaves between the slices.", "Drizzle generously with extra virgin olive oil and balsamic glaze.", "Sprinkle with sea salt and black pepper before serving."] ],

            // --- ASIAN ---
            [ 'category' => "Asian", 'title' => "Sushi Roll Platter", 'image' => "https://images.unsplash.com/photo-1579871494447-9811cf80d66c", 'meta' => [ 'time' => "60", 'servings' => "2", 'calories' => "400" ], 'ingredients' => [[ 'name' => "Sushi Rice", 'amount' => "2 cups" ], [ 'name' => "Nori", 'amount' => "5 sheets" ], [ 'name' => "Fish/Veg", 'amount' => "Assorted" ]], 'instructions' => ["Rinse sushi rice until water runs clear, then cook according to package instructions.", "Season cooked rice with sushi vinegar, sugar, and salt while fanning to cool.", "Place a sheet of Nori on a bamboo mat and spread a thin layer of rice.", "Arranged your choice of fish or vegetables in a line across the center.", "Roll the mat tightly away from you to form a cylinder.", "Slice into bite-sized pieces with a sharp wet knife."] ],
            [ 'category' => "Asian", 'title' => "Spicy Ramen", 'image' => "https://images.unsplash.com/photo-1569718212165-3a8278d5f624", 'meta' => [ 'time' => "30", 'servings' => "1", 'calories' => "450" ], 'ingredients' => [[ 'name' => "Ramen Noodles", 'amount' => "1 pack" ], [ 'name' => "Broth", 'amount' => "2 cups" ], [ 'name' => "Eggs", 'amount' => "1" ]], 'instructions' => ["Bring chicken or pork broth to a simmer; add soy sauce, miso, and chili oil to taste.", "In a separate pot, boil ramen noodles for 2-3 minutes until chewy; drain.", "Soft boil an egg (6-7 minutes), peel, and slice in half.", "Place noodles in a bowl, pour over the hot broth.", "Top with egg, sliced green onions, nori, and sesame seeds."] ],
            [ 'category' => "Asian", 'title' => "Chicken Pad Thai", 'image' => "https://images.unsplash.com/photo-1559314809-0d155014e29e", 'meta' => [ 'time' => "25", 'servings' => "2", 'calories' => "500" ], 'ingredients' => [[ 'name' => "Rice Noodles", 'amount' => "200g" ], [ 'name' => "Peanuts", 'amount' => "50g" ], [ 'name' => "Tamarind Sauce", 'amount' => "3 tbsp" ]], 'instructions' => ["Soak rice noodles in warm water for 20 minutes until flexible.", "Sear chicken pieces in a hot wok until cooked through; push to side.", "Crack an egg into the wok and scramble.", "Add soaked noodles and tamarind sauce, tossing vigorously to coat.", "Top with crushed peanuts, bean sprouts, and a squeeze of lime."] ],
            [ 'category' => "Asian", 'title' => "Beef Stir Fry", 'image' => "https://images.unsplash.com/photo-1512058564366-18510be2db19", 'meta' => [ 'time' => "20", 'servings' => "2", 'calories' => "400" ], 'ingredients' => [[ 'name' => "Beef Strips", 'amount' => "300g" ], [ 'name' => "Broccoli", 'amount' => "1 head" ], [ 'name' => "Soy Sauce", 'amount' => "2 tbsp" ]], 'instructions' => ["Slice beef against the grain into thin strips.", "Heat oil in a wok until smoking; sear beef batches for 1-2 mins.", "Remove beef, add broccoli and other veggies; stir-fry for 3-4 mins.", "Return beef to the pan, add soy sauce, ginger, and garlic.", "Toss everything together for 1 minute and serve over rice."] ],
            [ 'category' => "Asian", 'title' => "Vietnamese Pho", 'image' => "https://images.unsplash.com/photo-1582878826629-29b7ad1cdc43", 'meta' => [ 'time' => "120", 'servings' => "4", 'calories' => "450" ], 'ingredients' => [[ 'name' => "Beef Bones", 'amount' => "1kg" ], [ 'name' => "Rice Noodles", 'amount' => "1 pack" ], [ 'name' => "Herbs", 'amount' => "Plenty" ]], 'instructions' => ["Roast ginger and onion until charred; toast aromatic spices (anise, cloves).", "Simmer beef bones with charred aromatics for at least 3-4 hours.", "Strain broth and season with fish sauce and sugar.", "Place cooked rice noodles and thin slices of raw beef in a bowl.", "Pour boiling broth over the beef to cook it instantly. Garnish with fresh herbs."] ],

            // --- MEXICAN ---
            [ 'category' => "Mexican", 'title' => "Street Tacos", 'image' => "https://images.unsplash.com/photo-1565299585323-38d6b0865b47", 'meta' => [ 'time' => "20", 'servings' => "3", 'calories' => "400" ], 'ingredients' => [[ 'name' => "Corn Tortillas", 'amount' => "6" ], [ 'name' => "Carne Asada", 'amount' => "300g" ], [ 'name' => "Onion/Cilantro", 'amount' => "Topping" ]], 'instructions' => ["Marinate steak in citrus and spices provided in the ingredients.", "Grill meat over high heat until charred; let rest, then chop.", "Warm corn tortillas on a dry skillet until pliable.", "Fill each tortilla with a generous amount of chopped meat.", "Top with diced white onion, fresh cilantro, salsa, and lime juice."] ],
            [ 'category' => "Mexican", 'title' => "Loaded Nachos", 'image' => "https://images.unsplash.com/photo-1513456852971-30c0b8199d4d", 'meta' => [ 'time' => "15", 'servings' => "4", 'calories' => "600" ], 'ingredients' => [[ 'name' => "Tortilla Chips", 'amount' => "1 bag" ], [ 'name' => "Cheese", 'amount' => "200g" ], [ 'name' => "Jalapeños", 'amount' => "Sliced" ]], 'instructions' => ["Preheat oven to 200°C (400°F).", "Spread tortilla chips in a single layer on a baking sheet.", "Generously sprinkle shredded cheese over the chips.", "Add sliced jalapenos, black beans, or cooked beef if desired.", "Bake for 5-7 minutes until cheese is fully melted. Serve with salsa and sour cream."] ],
            [ 'category' => "Mexican", 'title' => "Chicken Quesadilla", 'image' => "https://images.unsplash.com/photo-1618040996337-56904b7850b9", 'meta' => [ 'time' => "10", 'servings' => "2", 'calories' => "500" ], 'ingredients' => [[ 'name' => "Tortillas", 'amount' => "2 large" ], [ 'name' => "Cheese", 'amount' => "1 cup" ], [ 'name' => "Chicken", 'amount' => "Cooked" ]], 'instructions' => ["Place a large flour tortilla on a heated skillet.", "Sprinkle half of the tortilla with shredded cheese and cooked chicken.", "Fold the tortilla in half over the filling.", "Cook for 2-3 minutes per side until golden brown and crispy.", "Slice into wedges and serve with guacamole or salsa."] ],
            [ 'category' => "Mexican", 'title' => "Guacamole & Chips", 'image' => "images/ingredients/avocado.jpg", 'meta' => [ 'time' => "10", 'servings' => "4", 'calories' => "300" ], 'ingredients' => [[ 'name' => "Avocado", 'amount' => "3" ], [ 'name' => "Lime", 'amount' => "1" ], [ 'name' => "Salt", 'amount' => "Pinch" ]], 'instructions' => ["Cut ripe avocados in half, remove pit, and scoop flesh into a bowl.", "Mash with a fork to your desired consistency (chunky or smooth).", "Squeeze in juice of one fresh lime and season with salt.", "Fold in diced onions, cilantro, and tomatoes if available.", "Serve immediately with fresh tortilla chips."] ],

            // --- MIDDLE EASTERN ---
            [ 'category' => "Middle Eastern", 'title' => "Royal Couscous", 'image' => "images/ingredients/Couscous.jpg", 'meta' => [ 'time' => "40", 'servings' => "4", 'calories' => "500" ], 'ingredients' => [[ 'name' => "Couscous", 'amount' => "500g" ], [ 'name' => "Vegetables", 'amount' => "Assorted" ], [ 'name' => "Chickpeas", 'amount' => "1 can" ]], 'instructions' => ["Prepare couscous by steaming or soaking in boiling water/stock with butter.", "In a large pot, sauté onions, spices (cumin, turmeric), and root vegetables.", "Add chickpeas, zucchini, and broth; simmer until vegetables are tender.", "Fluff the couscous with a fork to remove any lumps.", "Mound couscous on a platter and arrange the vegetable stew on top."] ],
            [ 'category' => "Middle Eastern", 'title' => "Falafel Wrap", 'image' => "images/ingredients/falafel.jpg", 'meta' => [ 'time' => "30", 'servings' => "2", 'calories' => "450" ], 'ingredients' => [[ 'name' => "Falafel", 'amount' => "6 balls" ], [ 'name' => "Pita", 'amount' => "2" ], [ 'name' => "Tahini", 'amount' => "Drizzle" ]], 'instructions' => ["Deep fry or bake falafel balls until dark golden brown and crispy.", "Warm pita bread in a pan or oven until soft and pliable.", "Layer pita with hummus, lettuce, tomatoes, and cucumber.", "Place 3 hot falafel balls in each pita gently smashing them.", "Drizzle generously with tahini sauce and roll up tight."] ],
            [ 'category' => "Middle Eastern", 'title' => "Hummus Plate", 'image' => "https://images.unsplash.com/photo-1637949385162-e416fb15b2ce", 'meta' => [ 'time' => "10", 'servings' => "2", 'calories' => "300" ], 'ingredients' => [[ 'name' => "Chickpeas", 'amount' => "1 can" ], [ 'name' => "Tahini", 'amount' => "2 tbsp" ], [ 'name' => "Olive Oil", 'amount' => "Drizzle" ]], 'instructions' => ["Drain chickpeas (reserving liquid) and blend with tahini, lemon juice, and garlic.", "Add cold water or aquafaba gradually while blending for fluffiness.", "Spoon onto a shallow plate, using a spoon to create swirls.", "Top with olive oil, paprika, parsley, and whole chickpeas.", "Serve immediately with warm pita bread or veggie sticks."] ],

            // --- AMERICAN ---
            [ 'category' => "American", 'title' => "Classic Cheeseburger", 'image' => "https://images.unsplash.com/photo-1568901346375-23c9450c58cd", 'meta' => [ 'time' => "20", 'servings' => "1", 'calories' => "700" ], 'ingredients' => [[ 'name' => "Beef Patty", 'amount' => "1" ], [ 'name' => "Bun", 'amount' => "1" ], [ 'name' => "Cheddar", 'amount' => "1 slice" ]], 'instructions' => ["Form beef into a patty slightly wider than your bun; season well with salt/pepper.", "Grill or fry on high heat for 3-4 minutes per side for medium.", "Add cheese slice in the last minute of cooking; cover to melt.", "Toast the bun until golden brown on the cut sides.", "Assemble burger with lettuce, tomato, pickles, and preferred condiments."] ],
            [ 'category' => "American", 'title' => "Mac and Cheese", 'image' => "https://images.unsplash.com/photo-1543339308-43e59d6b73a6", 'meta' => [ 'time' => "30", 'servings' => "4", 'calories' => "600" ], 'ingredients' => [[ 'name' => "Macaroni", 'amount' => "500g" ], [ 'name' => "Cheddar", 'amount' => "300g" ], [ 'name' => "Milk", 'amount' => "1 cup" ]], 'instructions' => ["Boil macaroni in plenty of salted water until al dente; drain.", "Melt butter in a pan, whisk in flour, then slowly add milk to make a béchamel.", "Remove sauce from heat and stir in grated cheddar until fully melted and smooth.", "Combine pasta with the cheese sauce, ensuring every noodle is coated.", "Optional: Top with breadcrumbs and bake for 15 minutes for a crispy crust."] ],
            [ 'category' => "American", 'title' => "BBQ Ribs", 'image' => "images/ingredients/Fries.jpg", 'meta' => [ 'time' => "180", 'servings' => "4", 'calories' => "800" ], 'ingredients' => [[ 'name' => "Pork Ribs", 'amount' => "1 rack" ], [ 'name' => "BBQ Sauce", 'amount' => "1 bottle" ], [ 'name' => "Spices", 'amount' => "Rub" ]], 'instructions' => ["Remove membrane from ribs and coat thoroughly with dry spice rub.", "Wrap in foil and bake low and slow at 150°C (300°F) for 2.5 - 3 hours.", "Unwrap ribs and brush generously with BBQ sauce.", "Broil or grill on high heat for 5-10 minutes to caramelize the sauce.", "Let rest for 10 minutes before slicing between the bones."] ],
            [ 'category' => "American", 'title' => "Grilled Cheese", 'image' => "https://images.unsplash.com/photo-1528735602780-2552fd46c7af", 'meta' => [ 'time' => "10", 'servings' => "1", 'calories' => "400" ], 'ingredients' => [[ 'name' => "Bread", 'amount' => "2 slices" ], [ 'name' => "Cheese", 'amount' => "Lots" ], [ 'name' => "Butter", 'amount' => "1 tbsp" ]], 'instructions' => ["Butter one side of each slice of bread completely.", "Place one slice butter-side down in a skillet over medium-low heat.", "Add a generous amount of cheese and top with the second slice (butter-side up).", "Cook until bottom is golden, then flip and cook the other side.", "Slice diagonally and serve hot while cheese is gooey."] ],
            [ 'category' => "American", 'title' => "Caesar Salad", 'image' => "https://images.unsplash.com/photo-1550304943-4f24f54ddde9", 'meta' => [ 'time' => "15", 'servings' => "2", 'calories' => "350" ], 'ingredients' => [[ 'name' => "Romaine", 'amount' => "1 head" ], [ 'name' => "Croutons", 'amount' => "Handful" ], [ 'name' => "Parmesan", 'amount' => "Shaved" ]], 'instructions' => ["Wash and chop Romaine lettuce into bite-sized pieces; dry darker leaves.", "Toss lettuce in a large bowl with Caesar dressing until evenly coated.", "Add croutons and toss again gently.", "Top with plenty of shaved Parmesan cheese and fresh cracked black pepper.", "For a protein boost, add sliced grilled chicken breast or shrimp."] ],

            // --- BREAKFAST ---
            [ 'category' => "Breakfast", 'title' => "Fluffy Pancakes", 'image' => "https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445", 'meta' => [ 'time' => "20", 'servings' => "2", 'calories' => "400" ], 'ingredients' => [[ 'name' => "Flour", 'amount' => "1 cup" ], [ 'name' => "Milk", 'amount' => "1 cup" ], [ 'name' => "Egg", 'amount' => "1" ]], 'instructions' => ["In a bowl, mix flour, sugar, baking powder, and a pinch of salt.", "In another bowl, whisk milk, egg, and melted butter.", "Combine wet and dry ingredients gently; do not overmix (lumps are okay).", "Pour batter onto a hot, buttered griddle.", "Flip when bubbles form on the surface; cook until golden brown."] ],
            [ 'category' => "Breakfast", 'title' => "French Toast", 'image' => "https://images.unsplash.com/photo-1484723091739-30a097e8f929", 'meta' => [ 'time' => "15", 'servings' => "2", 'calories' => "450" ], 'ingredients' => [[ 'name' => "Bread", 'amount' => "4 slices" ], [ 'name' => "Eggs", 'amount' => "2" ], [ 'name' => "Cinnamon", 'amount' => "1 tsp" ]], 'instructions' => ["Whisk eggs, milk, cinnamon, and a splash of vanilla in a shallow dish.", "Dip each slice of bread into the mixture, ensuring both sides are soaked.", "Melt butter in a pan over medium heat.", "Fry bread for 2-3 minutes per side until golden and slightly crispy.", "Serve immediately, dusted with powdered sugar and maple syrup."] ],
            [ 'category' => "Breakfast", 'title' => "Eggs Benedict", 'image' => "https://images.unsplash.com/photo-1608039829572-78524f79c4c7", 'meta' => [ 'time' => "30", 'servings' => "2", 'calories' => "500" ], 'ingredients' => [[ 'name' => "English Muffin", 'amount' => "2" ], [ 'name' => "Poached Eggs", 'amount' => "2" ], [ 'name' => "Hollandaise", 'amount' => "Sauce" ]], 'instructions' => ["Split and toast English muffins.", "Poach eggs in simmering water with vinegar for 3-4 minutes (soft yolk).", "Cook Canadian bacon or ham in a skillet.", "Place meat on muffin, top with poached egg.", "Pour warm Hollandaise sauce over the top and garnish with chives."] ],

            // --- DESSERT ---
            [ 'category' => "Dessert", 'title' => "Chocolate Lava Cake", 'image' => "images/ingredients/Chocolate.jpg", 'meta' => [ 'time' => "25", 'servings' => "2", 'calories' => "500" ], 'ingredients' => [[ 'name' => "Dark Chocolate", 'amount' => "100g" ], [ 'name' => "Butter", 'amount' => "50g" ], [ 'name' => "Sugar", 'amount' => "50g" ]], 'instructions' => ["Preheat oven to 200°C (400°F). Grease and flour ramekins.", "Melt chocolate and butter together in a double boiler or microwave.", "Whisk eggs and sugar until pale; fold into the chocolate mixture.", "Stir in flour just until combined; pour batter into ramekins.", "Bake for 12-14 minutes—sides should be firm but center soft. Serve warm."] ],
            [ 'category' => "Dessert", 'title' => "Strawberry Cheesecake", 'image' => "https://images.unsplash.com/photo-1533134242443-d4fd215305ad", 'meta' => [ 'time' => "60", 'servings' => "8", 'calories' => "450" ], 'ingredients' => [[ 'name' => "Cream Cheese", 'amount' => "500g" ], [ 'name' => "Biscuits", 'amount' => "Base" ], [ 'name' => "Strawberries", 'amount' => "Top" ]], 'instructions' => ["Crush biscuits and mix with melted butter; press into bottom of a springform pan.", "Beat cream cheese, sugar, and vanilla until smooth and creamy.", "Pour filling over the crust and smooth the top with a spatula.", "Refrigerate for at least 4 hours or overnight until set.", "Top with fresh sliced strawberries and glaze before serving."] ],
            [ 'category' => "Dessert", 'title' => "Apple Pie", 'image' => "images/ingredients/Pie Crust.jpg", 'meta' => [ 'time' => "60", 'servings' => "8", 'calories' => "400" ], 'ingredients' => [[ 'name' => "Apples", 'amount' => "6" ], [ 'name' => "Pie Crust", 'amount' => "2" ], [ 'name' => "Cinnamon", 'amount' => "1 tbsp" ]], 'instructions' => ["Peel, core, and slice apples; toss with sugar and cinnamon.", "Line a pie dish with one crust; fill with the apple mixture.", "Top with the second crust, seal edges, and cut slits for steam to escape.", "Brush top with egg wash and sprinkle with sugar.", "Bake at 190°C (375°F) for 45-50 minutes until golden and bubbling."] ],
            [ 'category' => "Dessert", 'title' => "Tiramisu", 'image' => "images/ingredients/Tiramisu.jpg", 'meta' => [ 'time' => "40", 'servings' => "6", 'calories' => "500" ], 'ingredients' => [[ 'name' => "Ladyfingers", 'amount' => "1 pack" ], [ 'name' => "Mascarpone", 'amount' => "500g" ], [ 'name' => "Coffee", 'amount' => "Strong" ]], 'instructions' => ["Brew strong espresso and let cool mixed with a splash of liqueur (optional).", "Whisk mascarpone with sugar and egg yolks until creamy.", "Quickly dip ladyfingers in coffee (don't soak) and layer in a dish.", "Spread half the mascarpone mixture over the fingers; repeat layers.", "Dust top generously with cocoa powder and chill for 4 hours."] ],

            // --- HEALTHY ---
            [ 'category' => "Healthy", 'title' => "Quinoa Salad", 'image' => "https://images.unsplash.com/photo-1623428187969-5da2dcea5ebf", 'meta' => [ 'time' => "20", 'servings' => "2", 'calories' => "300" ], 'ingredients' => [[ 'name' => "Quinoa", 'amount' => "1 cup" ], [ 'name' => "Cucumber", 'amount' => "1" ], [ 'name' => "Lemon", 'amount' => "Dressing" ]], 'instructions' => ["Rinse quinoa and cook in water/stock for 15 minutes; fluff and cool.", "Dice cucumber, tomatoes, and red onion into small pieces.", "Whisk lemon juice, olive oil, salt, and pepper for the dressing.", "Toss quinoa with veggies and dressing in a large bowl.", "Garnish with fresh parsley or mint and serve chilled."] ],
            [ 'category' => "Healthy", 'title' => "Green Smoothie Bowl", 'image' => "images/ingredients/GreenSmoothieBowl.jpeg", 'meta' => [ 'time' => "10", 'servings' => "1", 'calories' => "250" ], 'ingredients' => [[ 'name' => "Spinach", 'amount' => "Handful" ], [ 'name' => "Banana", 'amount' => "1" ], [ 'name' => "Almond Milk", 'amount' => "1 cup" ]], 'instructions' => ["Freeze banana slices for at least 2 hours for a thick texture.", "Blend spinach, frozen banana, and a splash of almond milk until smooth.", "Pour into a bowl; the consistency should be like soft-serve ice cream.", "Top with chia seeds, granola, fresh berries, and coconut flakes.", "Serve immediately with a spoon."] ],
            [ 'category' => "Healthy", 'title' => "Roasted Veggies", 'image' => "https://images.unsplash.com/photo-1518843875459-f738682238a6", 'meta' => [ 'time' => "40", 'servings' => "4", 'calories' => "200" ], 'ingredients' => [[ 'name' => "Carrots", 'amount' => "3" ], [ 'name' => "Potatoes", 'amount' => "3" ], [ 'name' => "Herbs", 'amount' => "Mix" ]], 'instructions' => ["Preheat oven to 200°C (400°F).", "Wash and chop carrots, potatoes, and other root veggies into uniform chunks.", "Toss veggies in a bowl with olive oil, rosemary, thyme, salt, and pepper.", "Spread in a single layer on a baking sheet; do not crowd.", "Roast for 35-40 minutes, tossing halfway, until golden and tender."] ],

            // --- MORE GLOBAL ---
            [ 'category' => "Asian", 'title' => "Indian Butter Chicken", 'image' => "https://images.unsplash.com/photo-1588166524941-3bf61a9c41db", 'meta' => [ 'time' => "50", 'servings' => "4", 'calories' => "600" ], 'ingredients' => [[ 'name' => "Chicken Breast", 'amount' => "500g" ], [ 'name' => "Tomato Sauce", 'amount' => "2 cups" ], [ 'name' => "Cream", 'amount' => "1/2 cup" ]], 'instructions' => ["Marinate chicken chunks in yogurt and spices for 1 hour.", "Pan-fry chicken until browned but not fully cooked; set aside.", "In the same pan, simmer tomato purée with butter, cream, and fenugreek.", "Return chicken to the sauce and simmer for 15 minutes.", "Serve hot with naan bread or basmati rice."] ],
            [ 'category' => "European", 'title' => "Spanish Paella", 'image' => "https://images.unsplash.com/photo-1534080564583-6be75777b70a", 'meta' => [ 'time' => "60", 'servings' => "6", 'calories' => "550" ], 'ingredients' => [[ 'name' => "Rice", 'amount' => "2 cups" ], [ 'name' => "Saffron", 'amount' => "Pinch" ], [ 'name' => "Seafood", 'amount' => "Mix" ]], 'instructions' => ["Sauté onions, garlic, and peppers in a large paella pan.", "Add rice and toast for a minute; stir in saffron infused broth.", "Arrange seafood (shrimp, mussels) on top of the rice.", "Simmer without stirring until liquid is absorbed and a crust forms (socarrat).", "Let rest for 5 minutes before serving with lemon wedges."] ],
            [ 'category' => "European", 'title' => "Greek Gyros", 'image' => "https://images.unsplash.com/photo-1529006557810-274b9b2fc783", 'meta' => [ 'time' => "30", 'servings' => "2", 'calories' => "500" ], 'ingredients' => [[ 'name' => "Pita", 'amount' => "2" ], [ 'name' => "Lamb/Chicken", 'amount' => "Sliced" ], [ 'name' => "Tzatziki", 'amount' => "Dollop" ]], 'instructions' => ["Marinate meat with oregano, garlic, and lemon juice.", "Grill or pan-fry meat until cooked through and slightly charred.", "Warm pita breads lightly.", "Spread tzatziki on pita; top with meat, tomato, onion, and fries.", "Wrap tightly in foil to hold everything together."] ],
            [ 'category' => "European", 'title' => "French Onion Soup", 'image' => "https://images.unsplash.com/photo-1604152135912-04a022e23696?auto=format&fit=crop&w=400&q=80", 'meta' => [ 'time' => "60", 'servings' => "4", 'calories' => "300" ], 'ingredients' => [[ 'name' => "Onions", 'amount' => "5 large" ], [ 'name' => "Beef Broth", 'amount' => "1L" ], [ 'name' => "Gruyere", 'amount' => "Topping" ]], 'instructions' => ["Slice onions thinly and caramelize slowly in butter for 45 mins.", "Add beef broth, thyme, and a splash of wine; simmer for 20 mins.", "Ladle soup into oven-safe bowls.", "Top each bowl with a slice of toasted baguette and grated Gruyère.", "Broil until cheese is bubbly and browned."] ],
            [ 'category' => "European", 'title' => "Fish and Chips", 'image' => "images/ingredients/FishandChips.jpeg", 'meta' => [ 'time' => "30", 'servings' => "2", 'calories' => "700" ], 'ingredients' => [[ 'name' => "White Fish", 'amount' => "2 fillets" ], [ 'name' => "Batter", 'amount' => "Mix" ], [ 'name' => "Fries", 'amount' => "Portion" ]], 'instructions' => ["Heat oil in a deep fryer or large pot to 180°C (350°F).", "Make a beer batter with flour, baking powder, and cold beer.", "Dip fish fillets into batter and carefully lower into hot oil.", "Fry for 4-5 minutes until crisp and golden; drain on paper towels.", "Fry potato strips twice for extra crispy chips. Serve with tartar sauce."] ],
            [ 'category' => "European", 'title' => "Ratatouille", 'image' => "https://images.unsplash.com/photo-1572453800999-e8d2d1589b7c", 'meta' => [ 'time' => "60", 'servings' => "4", 'calories' => "250" ], 'ingredients' => [[ 'name' => "Zucchini", 'amount' => "2" ], [ 'name' => "Eggplant", 'amount' => "1" ], [ 'name' => "Tomato Sauce", 'amount' => "Base" ]], 'instructions' => ["Spread a layer of piperade (pepper/tomato sauce) in a baking dish.", "Slice eggplant, zucchini, squash, and tomatoes into thin rounds.", "Arrange vegetable slices in a spiral pattern over the sauce.", "Drizzle with olive oil and herbs de Provence; cover with parchment.", "Bake at 150°C (300°F) for 45-60 mins. Serve warm or cold."] ],

            // --- SOUTH AMERICAN ---
            [ 'category' => "South American", 'title' => "Empanadas", 'image' => "images/ingredients/Empanadas.jpg", 'meta' => [ 'time' => "60", 'servings' => "4", 'calories' => "350" ], 'ingredients' => [[ 'name' => "Dough", 'amount' => "Pack" ], [ 'name' => "Beef Mince", 'amount' => "300g" ], [ 'name' => "Olives", 'amount' => "Handful" ]], 'instructions' => ["Sauté beef mince with onions, cumin, paprika, and chopped green olives.", "Roll out pastry discs and place a spoonful of filling in the center.", "Fold the dough over to create a half-moon shape; crimp edges with a fork.", "Brush with egg wash for a golden finish.", "Bake at 200°C (400°F) for 20-25 minutes until puffed and golden brown."] ],
            [ 'category' => "South American", 'title' => "Ceviche", 'image' => "https://images.unsplash.com/photo-1535400255456-984241443b29", 'meta' => [ 'time' => "20", 'servings' => "2", 'calories' => "200" ], 'ingredients' => [[ 'name' => "White Fish", 'amount' => "300g" ], [ 'name' => "Limes", 'amount' => "5" ], [ 'name' => "Cilantro", 'amount' => "Bunch" ]], 'instructions' => ["Cut fresh, high-quality white fish into small, even cubes.", "Place fish in a glass bowl and cover completely with freshly squeezed lime juice.", "Refrigerate for 15-20 minutes until the fish turns opaque ('cooks').", "Mix in finely diced red onion, chili peppers, and chopped cilantro.", "Serve immediately with corn nuts or sweet potato slices."] ],
            [ 'category' => "South American", 'title' => "Feijoada", 'image' => "images/ingredients/Feijoada.jpg", 'meta' => [ 'time' => "180", 'servings' => "6", 'calories' => "700" ], 'ingredients' => [[ 'name' => "Black Beans", 'amount' => "500g" ], [ 'name' => "Pork", 'amount' => "Assorted cuts" ], [ 'name' => "Rice", 'amount' => "Side" ]], 'instructions' => ["Soak black beans overnight; drain and rinse.", "In a large heavy pot, sauté bacon and onions until fragrant.", "Add beans, pork cuts (sausage, ribs, loin), and water; simmer gently for 2-3 hours.", "Cook until beans are creamy and meat is falling off the bone.", "Serve over white rice with collard greens and orange slices."] ],
            [ 'category' => "South American", 'title' => "Arepas", 'image' => "images/ingredients/Arepas.jpg", 'meta' => [ 'time' => "30", 'servings' => "4", 'calories' => "300" ], 'ingredients' => [[ 'name' => "Corn Flour", 'amount' => "2 cups" ], [ 'name' => "Water", 'amount' => "2.5 cups" ], [ 'name' => "Cheese", 'amount' => "Filling" ]], 'instructions' => ["Mix pre-cooked corn flour (masharepa) with warm water and salt.", "Knead until smooth and let rest for 5 minutes.", "Form dough into patties about 1cm thick.", "Cook on a lightly oiled griddle for 5-7 mins per side until crusty.", "Slice open hot arepas and stuff with butter and shredded cheese."] ],

            // --- AFRICAN ---
            [ 'category' => "African", 'title' => "Jollof Rice", 'image' => "images/ingredients/Couscous.jpg", 'meta' => [ 'time' => "60", 'servings' => "4", 'calories' => "450" ], 'ingredients' => [[ 'name' => "Rice", 'amount' => "2 cups" ], [ 'name' => "Tomato", 'amount' => "4" ], [ 'name' => "Bell Pepper", 'amount' => "2" ]], 'instructions' => ["Blend tomatoes, scotch bonnet peppers, and onions into a smooth paste.", "Fry the tomato mixture in oil with curry powder and thyme until reduced.", "Stir in washed rice and chicken stock; cover tightly with foil and a lid.", "Simmer on low heat for 20-30 minutes so rice steams in the stew.", "Fluff with a fork and serve with fried plantains."] ],
            [ 'category' => "African", 'title' => "Bunny Chow", 'image' => "https://images.unsplash.com/photo-1596797038530-2c107229654b?auto=format&fit=crop&w=600&q=80", 'meta' => [ 'time' => "45", 'servings' => "2", 'calories' => "600" ], 'ingredients' => [[ 'name' => "Bread Loaf", 'amount' => "1/2" ], [ 'name' => "Curry", 'amount' => "Portion" ], [ 'name' => "Coriander", 'amount' => "Garnish" ]], 'instructions' => ["Prepare a rich mutton or vegetable bean curry with aromatic spices.", "Cut a loaf of unsliced white bread in half or quarters.", "Hollow out the soft center (crumb), leaving the crust as a bowl.", "Ladl hot curry into the bread bowl and top with the scooped-out bread.", "Garnish with coriander and eat with your hands."] ],
            [ 'category' => "African", 'title' => "Shakshuka", 'image' => "https://images.unsplash.com/photo-1590412200988-a436970781fa", 'meta' => [ 'time' => "30", 'servings' => "2", 'calories' => "350" ], 'ingredients' => [[ 'name' => "Eggs", 'amount' => "4" ], [ 'name' => "Tomato Sauce", 'amount' => "1 can" ], [ 'name' => "Bell Pepper", 'amount' => "1" ]], 'instructions' => ["Sauté onions, bell peppers, and garlic in a skillet until soft.", "Pour in canned tomatoes, cumin, paprika, and chili flakes; simmer for 10 mins.", "Make small wells in the sauce with a spoon and crack eggs into them.", "Cover pan and cook until whites are set but yolks are runny.", "Sprinkle with feta cheese and parsley; serve with crusty bread."] ],
            [ 'category' => "African", 'title' => "Tagine", 'image' => "images/ingredients/Tagine.jpg", 'meta' => [ 'time' => "90", 'servings' => "4", 'calories' => "500" ], 'ingredients' => [[ 'name' => "Chicken", 'amount' => "1kg" ], [ 'name' => "Apricots", 'amount' => "1 cup" ], [ 'name' => "Couscous", 'amount' => "Side" ]], 'instructions' => ["Brown chicken pieces in a tagine or heavy pot.", "Add onions, ginger, cinnamon, saffron, and stock.", "Stir in dried apricots and almonds; cover and simmer low for 45 mins.", "Cook until chicken is tender and sauce has thickened.", "Serve hot over fluffy couscous, garnished with fresh cilantro."] ],

            // --- EASTERN EUROPEAN ---
            [ 'category' => "European", 'title' => "Pierogi", 'image' => "images/ingredients/potato.avif", 'meta' => [ 'time' => "60", 'servings' => "4", 'calories' => "400" ], 'ingredients' => [[ 'name' => "Flour", 'amount' => "2 cups" ], [ 'name' => "Potatoes", 'amount' => "3" ], [ 'name' => "Cheese", 'amount' => "1 cup" ]], 'instructions' => ["Make a simple dough with flour, water, egg, and salt; let rest.", "Prepare filling by mashing boiled potatoes with cheese and fried onions.", "Roll dough thin and cut circles; place filling in center and fold to seal.", "Boil in salted water until they float to the surface.", "Sear in a pan with butter and serve with sour cream."] ],
            [ 'category' => "European", 'title' => "Borsch", 'image' => "images/ingredients/Tagine.jpg", 'meta' => [ 'time' => "90", 'servings' => "6", 'calories' => "250" ], 'ingredients' => [[ 'name' => "Beets", 'amount' => "3" ], [ 'name' => "Cabbage", 'amount' => "1/2 head" ], [ 'name' => "Beef", 'amount' => "300g" ]], 'instructions' => ["Simmer beef to create a rich broth; skim foam.", "Add diced potatoes and shredded cabbage to the broth.", "Sauté grated beets, carrots, and onions with tomato paste separately.", "Specifically add sautéed veggies to the pot and cook until tender.", "Finish with fresh dill, garlic, and a dollop of sour cream when serving."] ],
            [ 'category' => "European", 'title' => "Goulash", 'image' => "https://images.unsplash.com/photo-1604908176997-125f25cc6f3d", 'meta' => [ 'time' => "120", 'servings' => "4", 'calories' => "500" ], 'ingredients' => [[ 'name' => "Beef", 'amount' => "500g" ], [ 'name' => "Paprika", 'amount' => "3 tbsp" ], [ 'name' => "Onions", 'amount' => "2" ]], 'instructions' => ["Fry chopped onions in lard or oil until golden.", "Add cubed beef and brown on all sides; remove from heat to stir in paprika.", "Add water/stock, caraway seeds, and simmer covered for 1.5 - 2 hours.", "Add cubed carrots and potatoes in the last 30 minutes.", "Serve the thick stew with bread or dumplings."] ],

            // --- MORE SNACKS & DRINKS ---
            [ 'category' => "Asian", 'title' => "Bubble Tea", 'image' => "https://images.unsplash.com/photo-1558160074-4d7d8bdf4256", 'meta' => [ 'time' => "15", 'servings' => "1", 'calories' => "300" ], 'ingredients' => [[ 'name' => "Tapioca Pearls", 'amount' => "1/4 cup" ], [ 'name' => "Black Tea", 'amount' => "1 cup" ], [ 'name' => "Milk", 'amount' => "1/2 cup" ]], 'instructions' => ["Boil tapioca pearls for 20 mins until chewy; soak in sugar syrup.", "Brew strong black tea and let it cool completely.", "Pour pearls and syrup into a glass.", "Add ice cubes and pour tea over the ice.", "Top with milk or cream and insert a wide straw."] ],
            [ 'category' => "Dessert", 'title' => "Churros", 'image' => "images/ingredients/Churros.jpg", 'meta' => [ 'time' => "30", 'servings' => "4", 'calories' => "450" ], 'ingredients' => [[ 'name' => "Flour", 'amount' => "1 cup" ], [ 'name' => "Sugar", 'amount' => "1/2 cup" ], [ 'name' => "Cinnamon", 'amount' => "Tbsp" ]], 'instructions' => ["Boil water, butter, and sugar; stir in flour to make a dough.", "Let dough cool slightly, then beat in eggs one by one.", "Pipe strips of dough into hot oil using a star nozzle.", "Fry until golden brown and drain on paper towels.", "Roll warm churros in cinnamon sugar mix."] ],
            [ 'category' => "Dessert", 'title' => "Belgian Waffles", 'image' => "https://images.unsplash.com/photo-1562376552-0d160a2f238d", 'meta' => [ 'time' => "20", 'servings' => "2", 'calories' => "500" ], 'ingredients' => [[ 'name' => "Flour", 'amount' => "2 cups" ], [ 'name' => "Eggs", 'amount' => "2" ], [ 'name' => "Pearl Sugar", 'amount' => "Handful" ]], 'instructions' => ["Mix flour, yeast, milk, and eggs to form a sticky dough.", "Let dough rise in a warm place for 30 minutes.", "Fold in pearl sugar chunks right before cooking.", "Scoop dough onto a hot waffle iron.", "Cook until caramelized and crispy."] ],
            [ 'category' => "Asian", 'title' => "Mango Sticky Rice", 'image' => "https://images.unsplash.com/photo-1579954115545-a95591f28bfc", 'meta' => [ 'time' => "40", 'servings' => "2", 'calories' => "400" ], 'ingredients' => [[ 'name' => "Glutinous Rice", 'amount' => "1 cup" ], [ 'name' => "Coconut Milk", 'amount' => "1 cup" ], [ 'name' => "Mango", 'amount' => "1 ripe" ]], 'instructions' => ["Soak glutinous rice, then steam for 20 minutes.", "Simmer coconut milk with sugar and salt; mix half into cooked rice.", "Let rice sit for 10 minutes to absorb liquid.", "Slice ripe sweet mango.", "Serve rice topped with remaining coconut sauce and mango slices."] ],
            [ 'category' => "Asian", 'title' => "Spring Rolls", 'image' => "images/ingredients/SpringRolls.jpg", 'meta' => [ 'time' => "40", 'servings' => "4", 'calories' => "300" ], 'ingredients' => [[ 'name' => "Rice Paper", 'amount' => "1 pack" ], [ 'name' => "Shrimp", 'amount' => "200g" ], [ 'name' => "Herbs", 'amount' => "Mint/Basil" ]], 'instructions' => ["Cook shrimp and vermicelli noodles; let cool.", "Dip rice paper wrapper briefly in warm water to soften.", "Lay herbs, shrimp, and noodles in the center of the wrapper.", "Fold sides in and roll tightly into a cylinder.", "Serve fresh with hoisin or peanut dipping sauce."] ],
            [ 'category' => "Middle Eastern", 'title' => "Kebab", 'image' => "https://images.unsplash.com/photo-1555939594-58d7cb561ad1", 'meta' => [ 'time' => "30", 'servings' => "2", 'calories' => "500" ], 'ingredients' => [[ 'name' => "Lamb Mince", 'amount' => "400g" ], [ 'name' => "Spices", 'amount' => "Cumin/Coriander" ], [ 'name' => "Skewers", 'amount' => "Wood" ]], 'instructions' => ["Mix lamb mince with garlic, cumin, coriander, and chili.", "Knead mixture well until sticky.", "Mold handfuls of meat onto skewers in a long sausage shape.", "Grill over charcoal or in a pan, turning often.", "Serve with flatbread, yogurt, and pickled onions."] ],
            [ 'category' => "Asian", 'title' => "Miso Soup", 'image' => "https://images.unsplash.com/photo-1598514982205-f36b96d1e8d4", 'meta' => [ 'time' => "10", 'servings' => "2", 'calories' => "100" ], 'ingredients' => [[ 'name' => "Dashi Stock", 'amount' => "2 cups" ], [ 'name' => "Miso Paste", 'amount' => "2 tbsp" ], [ 'name' => "Tofu", 'amount' => "Cubed" ]], 'instructions' => ["Bring dashi stock to a gentle simmer (do not boil hard).", "Add cubed tofu and rehydrated wakame seaweed.", "Place miso paste in a ladle and dissolve with some hot broth.", "Stir dissolved miso back into the soup and remove from heat immediately.", "Garnish with sliced green onions."] ],
            [ 'category' => "Italian", 'title' => "Garlic Bread", 'image' => "images/ingredients/Mozzarella.png", 'meta' => [ 'time' => "15", 'servings' => "4", 'calories' => "300" ], 'ingredients' => [[ 'name' => "Baguette", 'amount' => "1" ], [ 'name' => "Butter", 'amount' => "100g" ], [ 'name' => "Garlic", 'amount' => "4 cloves" ]], 'instructions' => ["Preheat oven to 180°C (350°F).", "Mix softened butter with minced garlic and parsley.", "Slice baguette diagonally almost all the way through.", "Spread garlic butter generously between each slice.", "Wrap in foil and bake for 10-15 minutes until crispy."] ]
        ];

        foreach ($recipesData as $data) {
            $category = Category::firstOrCreate(
                ['name' => $data['category']],
                ['slug' => Str::slug($data['category'])]
            );

            
            $recipe = Recipe::create([
                'user_id' => $admin->id,
                'category_id' => $category->id,
                'title' => $data['title'],
                'description' => "A delicious " . $data['title'] . " recipe.", 
                'image_path' => $data['image'],
                'prep_time' => (int)$data['meta']['time'],
                'servings' => (int)$data['meta']['servings'],
                'calories' => (int)$data['meta']['calories'],
                'instructions' => implode("\n", $data['instructions']),
            ]);

            foreach ($data['ingredients'] as $ingData) {
                $ingredient = Ingredient::firstOrCreate(['name' => $ingData['name']]);
                
                $recipe->ingredients()->attach($ingredient->id, ['quantity' => $ingData['amount']]);
            }
        }
    }
}
